local terminal = "kitty"

hl.bind("SUPER + RETURN", hl.dsp.exec_cmd(terminal), { transparent = true })
hl.bind("SUPER + W", hl.dsp.window.close("activewindow"))
hl.bind("SUPER + ALT + Q", hl.dsp.exit())
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("hyprshot -m region"))
hl.bind("SUPER + SPACE", hl.dsp.exec_cmd("sherlock"))
hl.bind("SUPER + F", hl.dsp.window.fullscreen("activewindow"))
hl.bind("SUPER + S", hl.dsp.window.float({ window = "activewindow" }))

hl.bind("SUPER + H", hl.dsp.focus({ direction = 'l' }))
hl.bind("SUPER + J", hl.dsp.focus({ direction = 'd' }))
hl.bind("SUPER + K", hl.dsp.focus({ direction = 'u' }))
hl.bind("SUPER + L", hl.dsp.focus({ direction = 'r' }))

hl.bind("SUPER + 1", hl.dsp.focus({ workspace = "1" }))
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = "2" }))
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = "3" }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = "4" }))
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = "5" }))
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = "6" }))
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = "7" }))
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = "8" }))
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = "9" }))
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = "10" }))

hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = "1" }))
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = "2" }))
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = "3" }))
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = "4" }))
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = "5" }))
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = "6" }))
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = "7" }))
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = "8" }))
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = "9" }))
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = "10" }))

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl --player=spotify previous"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl --player=spotify next"), { locked = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pactl set-sink-volume 0 +5%"), { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pactl set-sink-volume 0 -5%"), { locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pactl set-sink-mute 0 toggle"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl --player=spotify play-pause"), { locked = true })
hl.bind("SUPER + XF86AudioRaiseVolume", hl.dsp.exec_cmd("playerctl --player=spotify volume 0.01+"), { locked = true })
hl.bind("SUPER + XF86AudioLowerVolume", hl.dsp.exec_cmd("playerctl --player=spotify volume 0.01-"), { locked = true })

hl.bind("SUPER + mouse:272", hl.dsp.window.drag())
hl.bind("SUPER + mouse:273", hl.dsp.window.resize())

hl.dsp.submap("reset")
hl.bind("SUPER + R", hl.dsp.submap("resize-window"))
hl.define_submap("resize-window", function()
    hl.bind("l", hl.dsp.window.resize({ x = 10, y = 0, relative = true, window = "activewindow" }), { repeating = true })
    hl.bind("h", hl.dsp.window.resize({ x = -10, y = 0, relative = true, window = "activewindow" }), { repeating = true })
    hl.bind("h", hl.dsp.window.resize({ x = 0, y = -10, relative = true, window = "activewindow" }), { repeating = true })
    hl.bind("j", hl.dsp.window.resize({ x = 0, y = 10, relative = true, window = "activewindow" }), { repeating = true })
    hl.bind("RETURN", hl.dsp.submap("reset"))
end)

hl.bind("SUPER + CTRL + q", hl.dsp.exec_cmd("hyprlock"))
