general {
    hide_cursor = true
}

background {
    monitor = HDMI-A-1
    path = /home/ayaka/wallpapers/macintosh.jpg
    # color = rgba(25, 255, 20, 1.0)
    # NOTE: if they ever support gradients this is it
    # color = rgba(c91d78ff) rgba(6610c1ff) 45deg
    blur_passes = 1                     # Number of blur passes (1+)
    blur_size = 3                       # Blur radius
    # noise = 0.0117                      # Add a bit of noise (optional)
    # contrast = 0.8916                   # Adjust contrast (optional)
    # brightness = 0.8172                 # Adjust brightness (optional)
}

background {
    monitor = HDMI-A-2
    path = /home/ayaka/wallpapers/macintosh.jpg
    # color = rgb(201, 29, 120) rgb(102, 16, 193) 45deg
    # color = rgba(25, 255, 20, 1.0)
    blur_passes = 1                     # Number of blur passes (1+)
    blur_size = 3                       # Blur radius
    # noise = 0.0117                      # Add a bit of noise (optional)
    # contrast = 0.8916                   # Adjust contrast (optional)
    # brightness = 0.8172                 # Adjust brightness (optional)
}

label {
    monitor =
    color = rgba(255, 255, 255, 0.7)
    text = cmd[update:600000] echo "$(date '+%A, %B %d')"
    valign = top
    font_size = 27
    font_family = SF Pro Display
    position = 0, -80
    text_align = center
}

label {
    monitor =
    color = rgba(255, 255, 255, 0.6)
    text = cmd[update:60000] echo "$(date +%k:%M)"
    text_align = center
    valign = top
    font_size = 110
    font_family = SF Pro Display Bold
    position = 0, -100
}

input-field {
    monitor = HDMI-A-1
    size = 200, 50
    outline_thickness = 2
    placeholder_text = Enter password
    font_color = rgba(200, 200, 200, 0.6)
    valign = bottom
    position = 0, 100

    fail_text = Wrong password

    fail_color = rgba(255, 200, 200, 0.4)
    check_color = rgba(220, 220, 220, 0.6)
    outer_color = rgba(255, 255, 255, 0.2)
    inner_color = rgba(255, 255, 255, 0.15)

    dots_size = 0.2
    dots_size = 0.25
    font_family = SF Pro Text
    dots_spacing = 0.25
    dots_center = true
    dots_rounding = -1
    # dots_fade_time = 200
    dots_text_format = 
}
