general {
    hide_cursor = true
}

background {
    monitor = HDMI-A-1
    path = /home/ayaka/wallpapers/hallow.jpg
}

background {
    monitor = eDP-1
    path = /home/z/wallpapers/swirl.png
}

background {
    monitor = HDMI-A-2
    path = /home/ayaka/wallpapers/hallow.jpg
}

label {
    monitor =
    color = rgba(f5f5f5ce)
    text = cmd[update:600000] echo "$(date '+%A, %B %d')"
    valign = top
    font_size = 27
    font_family = SF Pro Display
    position = 0, -80
    text_align = center
}

label {
    monitor =
    color = rgba(f5f5f5ce)
    text = $TIME
    text_align = center
    valign = top
    font_size = 110
    font_family = SF Pro Display Bold
    position = 0, -100
}

input-field {
    monitor = HDMI-A-1
    size = 250, 40
    outline_thickness = 2
    placeholder_text = <span foreground="##ffffff7f">Enter password</span>
    valign = bottom
    position = 0, 100

    fail_text = Wrong password

    fail_color = rgba(ff453acc)
    check_color = rgba(ffffff88)
    outer_color = rgba(ffffff55)
    inner_color = rgba(ffffff33)
    font_color = rgba(ffffff7f)

    fade_on_empty = false

    hide_input = false

    dots_size = 0.25
    font_family = SF Pro Text
    dots_spacing = 0.25
    dots_center = true
    dots_rounding = -1
    # dots_fade_time = 200
    dots_text_format = 
}


input-field {
    monitor = eDP-1
    size = 250, 40
    outline_thickness = 2
    placeholder_text = <span foreground="##ffffff7f">Enter password</span>
    valign = bottom
    position = 0, 100

    fail_text = Wrong password

    fail_color = rgba(ff453acc)
    check_color = rgba(ffffff88)
    outer_color = rgba(ffffff55)
    inner_color = rgba(ffffff33)
    font_color = rgba(ffffff7f)

    fade_on_empty = false

    hide_input = false

    dots_size = 0.25
    font_family = SF Pro Text
    dots_spacing = 0.25
    dots_center = true
    dots_rounding = -1
    # dots_fade_time = 200
    dots_text_format = 
}
