general {
    hide_cursor = true
}

background {
    monitor = HDMI-A-1
    path = /home/ayaka/wallpapers/anime-codes.jpg
    # NOTE: if they ever support gradients this is it
    # color = rgba(c91d78ff) rgba(6610c1ff) 45deg
    blur_passes = 1                     # Number of blur passes (1+)
    blur_size = 2                       # Blur radius
}

background {
    monitor = HDMI-A-2
    path = /home/ayaka/wallpapers/anime-codes.jpg
    blur_passes = 1                     # Number of blur passes (1+)
    blur_size = 2                       # Blur radius
}

label {
    monitor =
    color = rgba(255, 255, 255, 0.7)
    text = cmd[update:600000] echo "$(date '+%A, %B %d')"
    valign = top
    font_size = 27
    font_family = SF Pro Display
    position = 0, -80
    text_align = center
}

label {
    monitor =
    color = rgba(255, 255, 255, 0.6)
    text = $TIME
    text_align = center
    valign = top
    font_size = 110
    font_family = SF Pro Display Bold
    position = 0, -100
}

input-field {
    monitor = HDMI-A-1
    size = 250, 40
    outline_thickness = 2
    placeholder_text = <span foreground="##ffffff7f">Enter password</span>
    font_color = rgba(200, 200, 200, 0.6)
    valign = bottom
    position = 0, 100

    fail_text = Wrong password

    fail_color = rgba(255, 200, 200, 0.4)
    check_color = rgba(220, 220, 220, 0.6)
    outer_color = rgba(255, 255, 255, 0.2)
    inner_color = rgba(255, 255, 255, 0.15)

    fade_on_empty = false

    hide_input = false

    dots_size = 0.25
    font_family = SF Pro Text
    dots_spacing = 0.25
    dots_center = true
    dots_rounding = -1
    # dots_fade_time = 200
    dots_text_format = 
}
